openapi: 3.0.0
info:
  version: 1.0.0
  title: Growth API
  description: Growth Planz 문서입니닷
servers:
  - url: 'http://localhost:8080/api'

paths:
  #get pormising Info
  /promisings/{promisingId}:
    get:
      tags:
        - promisings
      summary: get promising Info API
      parameters:
      - in: path
        name: promisingId
        schema:
          type: integer 
          example: 1
        required: true
      responses:
        '200':
          description: OK
        '404':
          description: NotFoundException
        '400':
          description: ValidationException

  #create Promising
  /promisings:
    post:
      tags:
        - promisings
      summary: create Promising Api
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                promisingName: 
                  type: string 
                  example: 하체 득근 운동
                  required: true
                ownerId: 
                  type: integer 
                  example: 1
                  required: true
                categoryId: 
                  type: integer 
                  example: 1
                  required: true
                minTime: 
                  type: date
                  example: "Fri Jun 10 2022 00:42:55 GMT+0900 (한국 표준시)"
                  required: true
                maxTime:
                  type: date
                  example: "Fri Jun 10 2022 05:42:55 GMT+0900 (한국 표준시)"
                  required: true
      responses:
        '200':
          description: created
        '404':
          description: NotFoundException
        '400':
          description: ValidationException

  #promsiing timeResponse
  /promisings/{promisingId}/time-response:
    post:
      tags:
        - promisings
      summary: promising response time
      parameters:
        - in: path  
          name: promisingId
          schema:
            type: integer 
          example: 1
          required: true

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                unit: 
                  type: integer 
                  example: 0.5
                  required: true
                timeTable: 
                  type: array 
                  items:
                    type: object
                    properties:
                      date:
                        type: date
                        example: "2022-05-20"
                      times:
                        type: array
                        example: [ true,true,true,true,true,true,true,true,true,true,true,true,true,true,true, false,true,true,true,true,true,true,true,true ,true,true] 
                  required: true
      responses:
        '200':
          description: OK
        '404':
          description: NotFoundException
        '400':
          description: ValidationException

